### PR TITLE
Added documentation page about manually installing GCP connectors

### PR DESCRIPTION
**Pull request by felix-melligan**

### CODE REVIEW

**Comment by netapp-bcammett** [comment]
@felix-melligan, is using the SDK a common way for customers to deploy a Connector? Or is it rare?

**Comment by felix-melligan** [comment]
@netapp-bcammett it's very common, especially for secure customers. As common as deploying from AWS/Azure marketplace

**Comment by netapp-bcammett** [comment]
@felix-melligan, thanks for confirming. We actually have a new feature that enables us to create "tabs" that show multiple ways to achieve the same result. For example:

image

Other than how to create the Connector, most of this new page has the same content as the existing page:
https://docs.netapp.com/us-en/occm/task_creating_connectors_gcp.html

So it would be better to update the existing page by adding two tabs under "Creating a Connector in GCP"
- One for creating it from the Cloud Manager interface
- One for creating it by using the Google SDK

I'll draft this up and send you a draft when it's ready.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
@felix-melligan, I integrated the changes through pull request #743. Here's the updated page:

https://docs.netapp.com/us-en/occm/task_creating_connectors_gcp.html#creating-a-connector-in-gcp

Let me know what you think.

**Pull request closed without merging**
